apiVersion: v1

kind: Pod

metadata:
  labels:
    test: liveness

  name: liveness-exec

spec:
  containers:
    - name: liveness
      image: busybox
      args:
        - /bin/sh
        - -c
        - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600  # 30s后删除/tmp/healthy文件，然后休眠600s
      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/healthy

        initialDelaySeconds: 5
        periodSeconds: 5
