apiVersion: v1
kind: Pod
metadata:
  name: mysql-tools-pod
spec:
  containers:
    - name: mysql-tools
      image: mysql:8.0.22
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: mysql666.
