apiVersion: v1
kind: Pod
metadata:
  name: nfs-pod
spec:
  containers:
    - image: nginx
      name: test-container
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: test-volume
  volumes:
    - name: test-volume
      nfs:
        server: 192.168.100.3
        path: /nfs/data
        readOnly: true
