apiVersion: v1
kind: Pod
metadata:
  name: probe-use-pod
spec:
  containers:
    - name: probe-use-container
      image: nginx
      ports:
        - name: http-port
          containerPort: 80
      livenessProbe:
        httpGet:
          path: /index.html
          port: http-port
        initialDelaySeconds: 15
        periodSeconds: 20
        failureThreshold: 4
      readinessProbe:
        httpGet:
          path: /index.html
          port: http-port
        initialDelaySeconds: 5
        periodSeconds: 10
        failureThreshold: 2
        timeoutSeconds: 1
      startupProbe:
        httpGet:
          path: /index.html
          port: http-port
        initialDelaySeconds: 10
        periodSeconds: 10
        failureThreshold: 30
        timeoutSeconds: 1
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 200m
          memory: 200Mi
      volumeMounts:
        - name: share-data
          mountPath: /data
  volumes:
    - name: share-data
      emptyDir: {}
---

