apiVersion: v1
kind: Pod
metadata:
  name: configmap-test-pod
spec:
  containers: # 容器列表
    - name: nginx
      image: 192.168.100.3:5000/nginx:latest
      imagePullPolicy: IfNotPresent
---

