apiVersion: v1
kind: ConfigMap # 创建修改脚本的容器卷
metadata:
  name: configmap2
data:
  test.txt: |
    hello world

---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-test-pod
spec:
  containers: # 容器列表
    - name: busybox1
      image: busybox
      volumeMounts:
        - name: bash-data
          mountPath: /data
      command: ["/bin/sh", "-c", "tail -f /dev/null"]

    - name: busybox2
      image: busybox
      volumeMounts:
        - name: bash-data
          mountPath: /data
      command: ["/bin/sh", "-c", "tail -f /dev/null"]
  volumes:
    - name: share-data # emptyDir类型的卷
      emptyDir: {}
    - name: bash-data
      configMap:
        name: configmap2
