apiVersion: v1
kind: Service
metadata:
  name: nginx-service-hello
spec:
  selector:
    app: nginx-hello
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-hello2
spec:
  selector:
    app: nginx-hello2
  ports:
    - port: 81
      targetPort: 80
  type: ClusterIP
