apiVersion: apps/v1
kind: Deployment
metadata:
  name: pv-deployment-nginx
  labels:
    app: pv-deployment-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pv-deployment-nginx
  template:
    metadata:
      labels:
        app: pv-deployment-nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: pv-claim
              mountPath: /usr/share/nginx/html
      volumes:
        - name: pv-claim
          persistentVolumeClaim:
            claimName: my-pvc
