apiVersion: apps/v1
kind: Deployment
metadata:
  name: readness-deployment-nginx
  labels:
    app: readness-deployment-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: readness-deployment-nginx
  template:
    metadata:
      labels:
        app: readness-deployment-nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /index1.html
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
            timeoutSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: readness-deployment-nginx
  labels:
    app: readness-deployment-nginx
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: readness-deployment-nginx
