apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-hello
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-hello
  template:
    metadata:
      labels:
        app: nginx-hello
    spec:
      initContainers:
        - name: init-busybox
          image: busybox
          command: ["sh", "-c", "echo hello world > /data/index.html"]
          volumeMounts:
            - name: share-data
              mountPath: /data
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: share-data
              mountPath: /usr/share/nginx/html
      volumes:
        - name: share-data
          emptyDir: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-hello2
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-hello2
  template:
    metadata:
      labels:
        app: nginx-hello2
    spec:
      initContainers:
        - name: init-busybox
          image: busybox
          command:
            ["sh", "-c", "echo hello world222222222222 > /data/index.html"]
          volumeMounts:
            - name: share-data
              mountPath: /data
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: share-data
              mountPath: /usr/share/nginx/html
      volumes:
        - name: share-data
          emptyDir: {}
